# 03 - Classification homework

In [4]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv("https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/course_lead_scoring_2026.csv")

In [7]:
df.head()

,lead_source,industry,employment_status,location,annual_income,number_of_courses_viewed,interaction_count,lead_score,converted
0,organic_search,technology,employed,europe,88160.0,3,4,0.64,1
1,social_media,technology,employed,south_america,72688.0,3,7,0.72,1
2,referral,retail,employed,europe,44697.0,3,4,0.58,1
3,paid_ads,manufacturing,student,NaN,NaN,3,6,0.57,0
4,referral,manufacturing,student,north_america,24062.0,4,5,0.62,1

In [14]:
df.isnull().sum()

lead_source                 148
industry                    240
employment_status           194
location                    208
annual_income               369
number_of_courses_viewed      0
interaction_count             0
lead_score                   35
converted                     0
dtype: int64

In [ ]:
df['lead_source'] = df['lead_source'].fillna('NA')
df['industry'] = df['industry'].fillna('NA')
df['employment_status'] = df['employment_status'].fillna('NA')
df['location'] = df['location'].fillna('NA')
df['annual_income'] = df['annual_income'].fillna(0)
df['lead_score'] = df['lead_score'].fillna(0)

df.isnull().sum()

,lead_source,industry,employment_status,location,annual_income,number_of_courses_viewed,interaction_count,lead_score,converted
0,organic_search,technology,employed,europe,88160.0,3,4,0.64,1
1,social_media,technology,employed,south_america,72688.0,3,7,0.72,1
2,referral,retail,employed,europe,44697.0,3,4,0.58,1
3,paid_ads,manufacturing,student,NA,0.0,3,6,0.57,0
4,referral,manufacturing,student,north_america,24062.0,4,5,0.62,1

## Question 1

In [18]:
df['industry'].sum()

'technologytechnologyretailmanufacturingmanufacturingmanufacturingeducationtechnologyhealthcareretailretailtechnologyNAretailretailretaileducationfinancemanufacturingfinanceeducationhealthcarehealthcarehealthcaretechnologyretailretaileducationNAmanufacturingNAeducationretailhealthcareretailhealthcareeducationhealthcaretechnologyeducationtechnologyeducationtechnologyfinancemanufacturingeducationeducationfinanceeducationfinanceeducationretailfinancetechnologytechnologyhealthcarehealthcarehealthcaremanufacturingretailhealthcarehealthcareretailretailtechnologyretailhealthcarehealthcareretailfinanceretailmanufacturingtechnologyNAfinanceeducationmanufacturingeducationretailhealthcaretechnologyfinanceeducationtechnologyeducationmanufacturingfinanceretaileducationfinancetechnologyeducationfinancetechnologyeducationretailfinancetechnologytechnologyretailretailmanufacturingeducationtechnologyfinancetechnologyfinancetechnologyNAeducationeducationtechnologytechnologyretailNAhealthcaretechnologyretailfinanceeducationtechnologytechnologyretailhealthcarehealthcaremanufacturingeducationhealthcarefinanceeducationmanufacturingeducationhealthcareretailtechnologyhealthcaretechnologytechnologyretailtechnologyfinanceretailhealthcarehealthcaretechnologytechnologymanufacturingeducationmanufacturingNAeducationtechnologyretailNAtechnologytechnologyeducationeducationeducationmanufacturingNAtechnologymanufacturingtechnologyretailtechnologytechnologyretailfinancefinanceeducationfinancefinancemanufacturingmanufacturingtechnologyfinanceretailretailtechnologytechnologyhealthcaretechnologyNANANAtechnologyretailretailmanufacturingeducationfinancetechnologytechnologyretailNAtechnologyfinanceretailNAtechnologyNAtechnologytechnologyhealthcarehealthcarefinancehealthcarehealthcareeducationtechnologyfinancetechnologytechnologytechnologytechnologytechnologyhealthcareretailhealthcareretailtechnologyretailretailhealthcaremanufacturingretailretailretailhealthcarehealthcareretailhealthcareNAeducationretaileducationhealthcaretechnologyretailmanufacturingmanufacturinghealthcareeducationeducationretailhealthcareretaileducationtechnologyhealthcaretechnologytechnologyfinancemanufacturingeducationhealthcarehealthcareeducationretailtechnologyfinancetechnologyhealthcaretechnologyfinancetechnologymanufacturinghealthcareretailhealthcareretaileducationretailretailtechnologyretailretailtechnologyeducationtechnologyhealthcarehealthcarehealthcaretechnologyhealthcareretailtechnologyhealthcareNAretailfinancehealthcarehealthcarefinanceNAtechnologyeducationhealthcareeducationretailhealthcaremanufacturingretailtechnologytechnologyretailhealthcaretechnologytechnologyeducationeducationretaileducationretailtechnologyfinancetechnologyretailmanufacturingeducationtechnologytechnologyhealthcaremanufacturingtechnologymanufacturingfinanceeducationretailhealthcareretailhealthcaretechnologyfinancetechnologyfinancetechnologyfinancetechnologytechnologyretailretailtechnologymanufacturingretaileducationNAhealthcareNAfinanceretailretailNAretailtechnologytechnologyeducationhealthcareretailmanufacturingfinancefinanceeducationtechnologyhealthcareNAretailtechnologyhealthcarefinancefinanceeducationfinancefinanceretailretailfinancetechnologytechnologyretailretailfinancehealthcaremanufacturingmanufacturingfinanceretailmanufacturingfinanceeducationhealthcareretailfinancefinanceeducationmanufacturingfinancemanufacturingNAfinancefinancetechnologyretailretailhealthcaretechnologyeducationmanufacturingretailtechnologyeducationretaileducationretaileducationtechnologymanufacturingtechnologytechnologytechnologyhealthcareeducationeducationhealthcarehealthcarehealthcaretechnologymanufacturingtechnologyfinancehealthcaretechnologyfinancehealthcareretailtechnologytechnologyretailhealthcareretailmanufacturingmanufacturinghealthcaretechnologyhealthcarefinanceeducationNAmanufacturinghealthcareNAeducationretaileducationNAeducationretailNAeducationtechnologytechnologyhealthcaretechnologyhealthcaretechnologyfinancehealthcareeducationfinanceeducationhealthcaretechnologytechnologymanufacturingfinancehealthcaretechnologyhealthcarefinancemanufacturinghealthcarehealthcaretechnologymanufacturingtechnologyretailfinanceeducationNAeducationfinanceretailtechnologyretailretailfinancetechnologyhealthcaretechnologytechnologyhealthcarefinancetechnologyretailhealthcareeducationtechnologytechnologyfinancetechnologytechnologyfinancehealthcarehealthcaretechnologyhealthcareretailtechnologyfinancemanufacturinghealthcaretechnologyfinancehealthcareeducationeducationhealthcareeducationeducationtechnologyfinancetechnologytechnologymanufacturingtechnologytechnologyfinancetechnologytechnologytechnologyfinanceNAeducationeducationmanufacturinghealthcarefinanceretailtechnologyretailmanufacturingmanufacturingfinancetechnologyhealthcaretechnologyretailretailNAretailretailfinancemanufacturingtechnologymanufacturingmanufacturingtechnologyretailfinancetechnologyretaileducationfinanceNAtechnologyeducationtechnologyhealthcarehealthcaretechnologymanufacturingfinancefinancefinanceNAtechnologyhealthcareretailretailtechnologyfinancetechnologytechnologyhealthcarefinancehealthcaremanufacturingretaileducationeducationeducationtechnologyeducationmanufacturingeducationeducationfinancefinancetechnologyhealthcareretailfinanceeducationtechnologyeducationeducationretailmanufacturingretailtechnologyfinancetechnologyeducationhealthcarefinancemanufacturinghealthcarefinancefinanceNAfinancemanufacturingretailfinanceretailretailtechnologymanufacturinghealthcarehealthcareretailtechnologyfinancemanufacturingfinanceretailtechnologyretailfinancefinancehealthcareretailretailhealthcarehealthcareretaileducationtechnologytechnologyNAtechnologymanufacturingtechnologyfinanceretailhealthcarehealthcarehealthcaretechnologyeducationhealthcaretechnologyretaileducationretailfinanceeducationtechnologyretailretailhealthcaretechnologyhealthcarefinanceretailhealthcareeducationtechnologyhealthcareeducationtechnologyeducationeducationretailmanufacturingmanufacturingfinanceeducationtechnologyNAeducationretailtechnologyeducationretaileducationNAfinancetechnologyretailhealthcareeducationretailretaileducationfinancetechnologyretailtechnologyretailhealthcarefinanceretailretailtechnologyeducationtechnologyeducationhealthcarefinanceeducationretailmanufacturinghealthcaretechnologytechnologytechnologymanufacturingeducationtechnologyfinanceretailhealthcarehealthcaremanufacturingretailtechnologyretaileducationhealthcareretailretailretailretailhealthcaretechnologymanufacturingmanufacturingNANAeducationfinancefinanceretailtechnologymanufacturinghealthcarefinanceeducationfinancetechnologytechnologyfinanceretailretailtechnologyfinancefinancemanufacturingfinanceretaileducationeducationmanufacturinghealthcaretechnologyfinanceretailretailretaileducationtechnologyhealthcareretailretailfinanceretailtechnologyNAfinanceeducationtechnologyhealthcareeducationretailhealthcareretailfinancetechnologyfinancetechnologymanufacturingmanufacturinghealthcareretailmanufacturingeducationfinancetechnologytechnologytechnologyeducationfinancefinancehealthcaremanufacturinghealthcareNAfinancetechnologymanufacturingNAeducationtechnologyfinancetechnologyNAretailtechnologyNAtechnologytechnologyfinancemanufacturingtechnologyfinanceNAhealthcaremanufacturingmanufacturingtechnologytechnologytechnologyhealthcaretechnologytechnologyhealthcareNAhealthcarefinancemanufacturingtechnologyfinancehealthcaremanufacturinghealthcareretailtechnologyhealthcarehealthcareretailretailhealthcaremanufacturingfinancehealthcareretailfinanceeducationretailfinancemanufacturingretailtechnologytechnologyNAhealthcareeducationmanufacturingmanufacturinghealthcaremanufacturingfinancehealthcarehealthcareretailretailretailtechnologyhealthcarehealthcareretailhealthcarehealthcaremanufacturingtechnologyhealthcarefinancehealthcarehealthcareretailtechnologytechnologyretailtechnologyretaileducationmanufacturinghealthcarehealthcareeducationeducationhealthcarehealthcaretechnologyeducationretailhealthcaretechnologytechnologyeducationtechnologytechnologyfinancetechnologyhealthcareretailretailhealthcaretechnologytechnologyhealthcaretechnologytechnologyhealthcarehealthcareeducationNANAeducationNAmanufacturingeducationfinanceeducationmanufacturingtechnologyfinancetechnologyhealthcaretechnologyretailtechnologyretaileducationtechnologytechnologytechnologymanufacturingtechnologyhealthcaretechnologyretailtechnologyfinancetechnologyretailretailretailhealthcareretailtechnologytechnologyfinancefinancefinancetechnologyfinancefinancemanufacturingeducationfinanceNAretaileducationfinanceeducationmanufacturinghealthcareeducationtechnologymanufacturinghealthcarefinancehealthcaremanufacturingtechnologyretailtechnologyretailtechnologytechnologyhealthcaretechnologyhealthcareeducationfinancetechnologyretailfinancehealthcarefinanceretailtechnologyfinancetechnologyfinanceeducationfinanceretailtechnologyeducationretailfinancemanufacturingretailfinancemanufacturinghealthcaretechnologyeducationhealthcaretechnologyfinancehealthcaretechnologymanufacturinghealthcaretechnologytechnologyhealthcareeducationtechnologyfinanceeducationhealthcarefinancefinancemanufacturingtechnologymanufacturingeducationeducationretailfinancehealthcareretailmanufacturingretailtechnologytechnologymanufacturingfinancefinanceeducationtechnologytechnologyretailtechnologyretailhealthcarefinanceeducationNAmanufacturingtechnologyhealthcarehealthcarehealthcareretailhealthcaretechnologyhealthcaretechnologyretailfinancemanufacturinghealthcarehealthcaretechnologyretailretailfinanceeducationhealthcarehealthcareeducationhealthcareretailNAmanufacturinghealthcaretechnologyretailhealthcareretailretailtechnologyfinanceretailfinanceeducationfinanceretaileducationretailretailretailfinanceeducationNAfinancehealthcarehealthcareeducationhealthcareretailhealthcaremanufacturingeducationeducationmanufacturingretailtechnologytechnologytechnologyhealthcaremanufacturinghealthcarehealthcareretailNAretailNAfinancehealthcareretailtechnologyretaileducationeducationretailNAretailfinancetechnologyeducationfinancetechnologytechnologyNAhealthcareeducationtechnologyhealthcarefinancemanufacturingtechnologytechnologyretailretailretailfinancefinancemanufacturingretailfinanceretailNAfinancefinanceeducationtechnologyhealthcarefinancehealthcarehealthcaretechnologytechnologytechnologytechnologyeducationtechnologyfinancetechnologyeducationhealthcaretechnologymanufacturingtechnologyeducationhealthcareeducationeducationretailhealthcaretechnologyretaileducationfinancehealthcareretailtechnologytechnologymanufacturingtechnologyhealthcaretechnologytechnologyNAhealthcaremanufacturingtechnologyeducationeducationfinanceretailfinancemanufacturinghealthcarehealthcaretechnologyhealthcaretechnologyfinanceretailmanufacturingretailtechnologyfinanceretailtechnologytechnologytechnologyretailmanufacturinghealthcaretechnologyhealthcaretechnologyhealthcareretailfinanceretailtechnologyfinancefinancefinanceretailretailretailfinanceretailtechnologytechnologyretailfinanceretailretailfinancehealthcaretechnologyfinancehealthcarefinancetechnologymanufacturingeducationretaileducationeducationretaileducationfinancehealthcaremanufacturingtechnologyfinancetechnologytechnologyretailfinancefinanceNAfinancefinanceretailfinanceeducationeducationNAtechnologyfinanceNAretailtechnologymanufacturinghealthcaremanufacturingfinancehealthcarehealthcaretechnologyfinancefinancefinanceretailtechnologyfinanceretaileducationmanufacturingtechnologyretailtechnologyfinancehealthcaretechnologyhealthcarefinancetechnologytechnologymanufacturingeducationmanufacturingeducationretailhealthcarefinancehealthcaretechnologytechnologyNAretailretailfinanceretailtechnologyeducationfinanceretailhealthcareeducationretaileducationtechnologytechnologyfinancetechnologytechnologyfinancefinancetechnologyretailfinanceretailretailretailretailretaileducationtechnologytechnologyhealthcaretechnologyretaileducationfinancehealthcarefinanceNAeducationfinanceeducationretailhealthcareNAretailfinancehealthcareeducationretailretailmanufacturingeducationmanufacturingretailhealthcareretailtechnologytechnologyhealthcareeducationhealthcaremanufacturinghealthcaretechnologytechnologyretaileducationretailNAretailtechnologytechnologytechnologyretailmanufacturingretailretaileducationfinancefinanceretailtechnologyfinancetechnologytechnologyretaileducationtechnologyfinancehealthcaretechnologyretailtechnologyfinancemanufacturinghealthcarefinanceretailretaileducationmanufacturingtechnologyhealthcarefinancefinancetechnologyNAhealthcaretechnologyretailfinancehealthcaremanufacturingtechnologyretailtechnologytechnologyfinanceretaileducationmanufacturingmanufacturingfinanceNAhealthcareeducationretailtechnologyhealthcarehealthcaremanufacturingeducationmanufacturingfinanceNAtechnologyhealthcareeducationretaileducationfinancetechnologyhealthcareeducationretailhealthcaretechnologyretailNAeducationhealthcaretechnologyhealthcarehealthcarehealthcarehealthcarehealthcareretailmanufacturinghealthcarefinanceNAhealthcareeducationeducationeducationretailhealthcarefinancetechnologyeducationNAhealthcarehealthcareeducationtechnologyhealthcareeducationhealthcaretechnologytechnologytechnologytechnologyhealthcareeducationtechnologymanufacturingretaileducationtechnologytechnologyhealthcarefinanceNAmanufacturingretailfinanceretaileducationNAhealthcareeducationmanufacturinghealthcareeducationhealthcarehealthcareeducationtechnologytechnologyretailtechnologyfinanceretailtechnologyhealthcaremanufacturingmanufacturingtechnologytechnologyeducationfinancefinanceretailtechnologyretailretailmanufacturinghealthcareretaileducationretaileducationretailtechnologyhealthcarehealthcaretechnologytechnologyhealthcarehealthcareeducationtechnologyNAretailhealthcaretechnologyeducationtechnologyeducationmanufacturingtechnologyeducationtechnologymanufacturingretailtechnologytechnologyNAretailretailmanufacturingtechnologyhealthcareretailhealthcareretailtechnologytechnologyfinanceeducationtechnologytechnologyfinancemanufacturinghealthcareNAfinancehealthcarefinancetechnologytechnologyretailtechnologyfinancemanufacturingmanufacturinghealthcarefinancefinancefinanceretailhealthcaretechnologyfinancetechnologyeducationtechnologyhealthcaretechnologyretailhealthcareretailmanufacturingretailfinancemanufacturinghealthcaretechnologyfinancetechnologytechnologyretaileducationtechnologytechnologyfinanceretailtechnologyhealthcarehealthcaretechnologyhealthcarefinancehealthcarehealthcarehealthcaremanufacturingfinanceNAhealthcaremanufacturingretailhealthcareretaileducationhealthcaretechnologytechnologytechnologymanufacturingtechnologymanufacturingretailretailhealthcarehealthcaremanufacturingfinancehealthcaretechnologyfinanceretaileducationhealthcaremanufacturingfinanceretailmanufacturingretailretailtechnologyretailNAeducationmanufacturingeducationeducationfinancemanufacturingretailfinancehealthcaretechnologytechnologyeducationtechnologyfinanceretailfinancetechnologyeducationtechnologymanufacturingeducationtechnologyeducationhealthcareretaileducationmanufacturingtechnologyretailhealthcarefinanceretailhealthcarehealthcaremanufacturingeducationretailtechnologyretailretailretailfinanceeducationfinanceretailretailmanufacturingtechnologymanufacturingNAeducationretailhealthcaremanufacturinghealthcareretailhealthcareeducationeducationmanufacturingtechnologyretailretailmanufacturingtechnologytechnologyretailtechnologytechnologytechnologytechnologyeducationeducationeducationtechnologyretailretailhealthcaretechnologyeducationeducationtechnologyhealthcarehealthcarehealthcareeducationhealthcareeducationfinancemanufacturingretailretailretailretailhealthcaretechnologyfinanceretailtechnologyNANAtechnologytechnologyhealthcarefinancehealthcareeducationeducationretailhealthcareretailmanufacturingretailfinancefinanceretailfinancemanufacturingtechnologytechnologyretailfinancetechnologyeducationeducationfinanceretailretailretailtechnologyretailmanufacturingretailfinancefinanceNAfinanceretaileducationretailtechnologyfinancetechnologyretailretailhealthcaretechnologyretailtechnologytechnologyeducationretaileducationtechnologyretailmanufacturingretailhealthcaremanufacturinghealthcarehealthcaremanufacturingretailmanufacturingeducationeducationretailfinancetechnologytechnologyretailtechnologyhealthcareretailtechnologyhealthcareNAeducationeducationmanufacturingeducationretaileducationfinanceretailmanufacturinghealthcarehealthcarehealthcarehealthcarehealthcarefinanceeducationfinanceNAretaileducationhealthcarehealthcareeducationfinanceeducationmanufacturingretailmanufacturingfinancemanufacturingfinancetechnologytechnologyretailretailNAtechnologyretailfinancemanufacturingfinancetechnologyeducationNAeducationhealthcareretailretailNAfinancetechnologyretailhealthcareeducationeducationhealthcareeducationeducationeducationeducationhealthcarehealthcaretechnologyeducationretailfinanceretailretailhealthcareeducationeducationfinancetechnologyfinancefinancetechnologyhealthcaretechnologyhealthcaretechnologytechnologyeducationfinancehealthcareeducationretailtechnologyfinanceNAmanufacturinghealthcaretechnologyretailfinancehealthcareeducationtechnologyfinancetechnologyhealthcarehealthcaretechnologytechnologytechnologyhealthcaretechnologyeducationNAfinanceeducationretailretailretailretailtechnologytechnologyretailhealthcaretechnologyhealthcareretailmanufacturingfinanceeducationhealthcarehealthcareNAeducationtechnologytechnologyfinancetechnologyhealthcaretechnologymanufacturingtechnologyhealthcareretailtechnologymanufacturingretaileducationtechnologyhealthcareeducationhealthcarehealthcarehealthcareeducationretailtechnologyretailhealthcarefinancetechnologyretailfinancetechnologytechnologyfinancemanufacturingtechnologyretailfinanceretailmanufacturinghealthcaretechnologyeducationeducationeducationfinancehealthcareeducationretailtechnologytechnologyeducationtechnologytechnologyeducationfinanceretailretailhealthcarehealthcarefinancetechnologytechnologymanufacturingmanufacturinghealthcareNAtechnologytechnologyretailhealthcareeducationretailfinancefinancetechnologyeducationretailhealthcareretaileducationNANAeducationtechnologyfinanceeducationeducationmanufacturinghealthcareeducationtechnologyretailtechnologyhealthcareeducationfinancehealthcareretailretailtechnologyretailretailfinancemanufacturingmanufacturingtechnologyNAfinanceeducationtechnologytechnologytechnologyhealthcaretechnologytechnologyeducationretaileducationfinancetechnologyretailretaileducationtechnologytechnologytechnologyfinancehealthcarefinancehealthcareNAretailretailfinancefinanceeducationhealthcaremanufacturingretailfinanceretailretailretailretailfinancefinancetechnologyNAeducationretailNANAfinanceeducationfinanceretailtechnologymanufacturingmanufacturingtechnologyhealthcarehealthcaretechnologyNAretailhealthcareNAhealthcareretailtechnologytechnologyretailfinancehealthcareretailmanufacturingtechnologytechnologyretailfinanceretailmanufacturingtechnologyeducationtechnologyretailfinancefinanceeducationtechnologyretailmanufacturingretailretailretailfinancehealthcareNAretailhealthcarefinanceeducationfinancetechnologytechnologymanufacturingretailmanufacturingtechnologyhealthcaretechnologyretailretailfinanceretailNAfinancetechnologyfinanceretailhealthcaretechnologymanufacturinghealthcarefinanceretailtechnologyfinancetechnologyeducationfinancetechnologyhealthcareeducationmanufacturingtechnologyeducationNAfinancehealthcarefinanceeducationfinanceeducationtechnologytechnologyeducationretailhealthcareeducationhealthcarehealthcaremanufacturinghealthcarehealthcareNAtechnologyretailtechnologytechnologytechnologyhealthcarefinanceNAhealthcareretailretailretailhealthcaretechnologyeducationhealthcaretechnologytechnologyeducationtechnologyretailfinanceretailNAretailfinancefinancemanufacturingtechnologyhealthcaremanufacturingtechnologytechnologyeducationtechnologyhealthcareNAfinanceeducationretaileducationtechnologyNAhealthcarehealthcaretechnologyhealthcarehealthcarefinancetechnologyhealthcarefinanceeducationhealthcarehealthcareretailtechnologyre